# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0 # Specify the version of Black you want to use
    hooks:
      - id: black
        name: black
        language_version: python3.12 # Ensure Python 3.12 is used to run Black
